// 拠点画面の什器・プロップのドット絵データ（第19弾試作: ローラー台・パーツ棚・木・チームカー）。
// scratchpad/w19/export.mjs（セル格子ジェネレータ＋目視プレビューの反復）で生成した静的データ。
// 1セル=0.5スクリーンpx（PixelPersonの0.49と粒度を揃えてある）。anchorは接地点（足元中央）の
// セル座標。legendの文字はファイル内のOBJ_LEGEND（木だけはpixelObject.jsxが季節パレットから動的に組む）。

export const OBJ_SPRITES = {
  rollerUnit: {
    anchorCol: 20, anchorRow: 17,
    rows: [
      "......................KKKK...............",
      "................K...KKrrrK...............",
      "..............KKcKKKrrrrrK...............",
      "............KKcceerrrrrrKK...............",
      "..........KKcceerrrrrrrK.................",
      "........KKcceerrrrrrrrRRK................",
      "......KKcceerrrrrrrrRRcccKK.....KKKK.....",
      "....KKccccrrrrrrrrRRcccccccKK.KKrrrK.....",
      "..KKccccrrrrrrrrRRcccccccccceKrrrrrK.....",
      "KKccccccrrrrrrRRcccccccccceerrrrrrrK.....",
      "KaccccccrrrrRRcccccccccceerrrrrrrrK......",
      "KaaaccccrrRRcccccccccceerrrrrrrrRRcKK....",
      "KaaaaacccccccccccccceerrrrrrrrRRcccccKK..",
      "KaaaaaaaccccccccccccrrrrrrrrRRcccccccccKK",
      "KaaaaaaaaaccccccccrrrrrrrrRRcccccccccccbK",
      "KKaaaaaaaaaaccccccrrrrrrRRcccccccccccbbbK",
      "..KKaaaaaaaaaaccccrrrrRRcccccccccccbbbbbK",
      "....KKaaaaaaaaaaccrrRRcccccccccccbbbbbbbK",
      "...KK.KKaaaaaaaaaacccccccccccccbbbbbbbbbK",
      "...KKKK.KKaaaaaaaaaacccccccccbbbbbbbbbbKK",
      ".....KKKK.KKaaaaaaaaaacccccbbbbbbbbbbKK..",
      ".......KKKK.KKaaaaaaaaaacbbbbbbbbbbKK....",
      ".........KKKK.KKKKKKKKKKKKKKKKKKKKK......",
    ],
  },
  partsShelf: {
    anchorCol: 22, anchorRow: 31,
    rows: [
      "................K............................",
      "..............KKyKK..........................",
      "............KKyyyyyKK........................",
      "..........KKyyyyyyyyyKK......................",
      "........KKyyyyyyyyyyyyyKK....................",
      "......KKyyyyyyyyyyyyyyyyyKK..................",
      "....KKyyyyyyyyyyyyyyyyyyyyyKK................",
      "..KKyyyyyyyyyyyyyyyyyyyyyyyyyKK..............",
      "KKyyyyyyyyyyyyyyyyyyyyyyyyyyyyyKK............",
      "KwyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyKK..........",
      "KwiiyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyKK........",
      "KwiiiiyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyKK......",
      "KwiiiiiiyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyKK....",
      "KwiiiiiiiiyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyKK..",
      "Kwiii44444iiyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyKK",
      "Kwzii11111iiiiyyyyyyyyyyyyyyyyyyyyyyyyyyyyyxK",
      "Kwzzz11111iiiiiiyyyyyyyyyyyyyyyyyyyyyyyyyxxxK",
      "Kwizz11111iiiiiiiiyyyyyyyyyyyyyyyyyyyyyxxxxxK",
      "Kwiii11111iiiiiiiiiiyyyyyyyyyyyyyyyyyxxxxxxxK",
      "Kwiiiiizzzziiii55555iiyyyyyyyyyyyyyxxxxxxxxxK",
      "Kwiiiiiiizzzzii22222iiiiyyyyyyyyyxxxxxxxxxxxK",
      "Kwiiiiiiiiizzzz22222iiiiiiyyyyyxxxxxxxxxxxxxK",
      "Kwziiiiiiiiiizz22222iiiiiiiiwwxxxxxxxxxxxxxxK",
      "Kwzzziiii66666i22222iiiiiiiiwwxxxxxxxxxxwxxxK",
      "Kwizzzzii33333iiizzzziiiiiiiwwxxxxxwxxxxwxxxK",
      "Kwiiizzzz33333iiiiizzzziiiiiwwxxxxxwxxxxwxxxK",
      "Kwiiiiizz33333iiiiiiizzzziiiwwxxxxxwxxxxwxxxK",
      "Kwiiiiiii33333iiiiiiiiizzzziwwxxxxxwxxxxwxxxK",
      "KKiiiiiiiirzzzziiiiiiiiiizzzwwxxxxxwxxxxwxxxK",
      "..KKiiiirrrrrzzzziiiiiiiiiizwwxxxxxwxxxxwxxxK",
      "....KKirrrirrrizzzziiiiiiiiiwwxxxxxwxxxxwxxxK",
      "......KrriiirriiizzzziiiiiiiwwxxxxxwxxxxwxxxK",
      "......KriiiiirriiiizzzziiiiiwwxxxxxwxxxxwxxxK",
      ".......KriiirriiiiiiizzzziiiwwxxxxxwxxxxwxxxK",
      ".......KrrirrKiiiiiiiiizzzziwwxxxxxwxxxxwxxKK",
      "........KKrKK.KKiiiiiiiiizzzwwxxxxxwxxxxwKK..",
      "..........K.....KKKKKKKKKKKKKKKKKKKKKKKKK....",
    ],
  },
  tree: {
    anchorCol: 22, anchorRow: 56,
    rows: [
      "............K.........K......................",
      "........KKKKtKKKKKKKKKtKKKKKKK.K.............",
      "......KKtvvvVvvvvvvvuuuuutttttKtKKKK.........",
      ".....KtvvVVVVVVVvvvvvvuuuuutttttttttK........",
      "....KtvVVVVVVVVVVVvvvvvuuuuuuttttttttK.......",
      "....KvvVVVVVVVVVVVvvvvvvuuuuuuttttttttK......",
      "...KvvVVVVVVVVVVVVVvvvvvvuuuuuutttttttK......",
      "....KvvVVVVVVVVVVVvvvvvvvuuuuuuutttttttK.....",
      "....KvvVVVVVVVVVVVvvvvvvvuuuuuuuutttttttK....",
      "...KvvvvvVVVVVVVvvvvvvvvvvuuuuuuuttttttttK...",
      "...KvvvvvvvvVvvvvvvvvvvvvuuuuuuuuutttttttK...",
      "..KuvvvvvvvvvvvvvvvvvvvTTuuuuuuuuuttttttttK..",
      "..KuvvvvvvvvvvvvvvvvvvvTvuuuuuuuuuttttttttK..",
      ".KtuuvvvvvvvvvvvvvvvvvvvuuuuuuuuuuuutttttttK.",
      ".KuuuuvvvvvvvvvvvvvvvvvuuuuuuuuuuuuTTutttttK.",
      ".KtuuuuvvvvvvvvvvvvvvvuuuuuuuuuuuuuTuuuttttK.",
      ".KtuuuuuvvvvvvvvvvvvvuuuuuuuuuuuuuuuuuuttttK.",
      ".KtuuuuuuvuvuvvvuvuvuuuuuuuuuuuuuuuuuuutttttK",
      "KttuuuuuuuTTuuvuuuuuuuuuuuuuuuuuuuuuuuuuttttK",
      ".KtuuuuuuuTuuuuuuuuuuuuuuuuuuuuuuuuuuuuutttK.",
      ".KttuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuttttK.",
      ".KtttuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuttttK.",
      ".KttttuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuttttK.",
      ".KtttttuuuuuuuuuuuuuuuuuuuuuTTuuuuuututttttK.",
      ".KttttttuuuuuuuuuuuuuuuuuuuuTtutututtttttttK.",
      "KttttttttuuuuuuuuuuuuuuuuuuutttttttttttttttK.",
      "KtttttttttutuuuuuuuuuuuuututttttttttttttttK..",
      ".KtttttttttttututuuutututtttttttttttttttttK..",
      ".KTtttttttttttttttutttttttttttttttttttttTTK..",
      "..KTttttttttttttttttttttttttttttttttttTTKK...",
      "...KTTTTttttttttttttttttttttttttttttTTKK.....",
      "....KKKKTTtttttttttttttttttttttttttTKK.......",
      "........KKTTtttttttttttttttttttttTTK.........",
      "..........KKTTTtttttttttttttttTTTKK..........",
      "............KKKTTTTTTTtTTTTTTTKKK............",
      "...............KKKKTTTTTTKKKKK...............",
      "...................KwwTxK....................",
      "...................KwwwxK....................",
      "...................KwwwxK....................",
      "...................KwwwxK....................",
      "..................KwwwwxxK...................",
      "..................KwwwwxxK...................",
      "..................KwwwwxxK...................",
      "..................KwwwwxxK...................",
      "..................KwwwwxxK...................",
      "..................KwwwwxxK...................",
      "..................KwwwwxxK...................",
      "..................KwwwwxxK...................",
      "..................KwwwwxxK...................",
      "..................KwwwwxxK...................",
      "..................KwwwwxxK...................",
      ".................KwwwwwxxxK..................",
      ".................KwwwwwxxxK..................",
      ".................KwwwwwxxxK..................",
      ".................KwwwwwxxxK..................",
      ".................KwwwwwxxxK..................",
      ".................KKKKKKKKKK..................",
    ],
  },
  treeSnow: {
    anchorCol: 22, anchorRow: 56,
    rows: [
      "............K.........K......................",
      "........KKKKSKKKKKKKKKtKKKKKKK.K.............",
      "......KKSSSSSSSSSSSSSSuuutStttKtKKKK.........",
      ".....KSSSSSSSSSSSSSSSSSSSSSSSSSSttttK........",
      "....KSSSSSSSSSSSSSSSSSSSSSSSSSSSSttttK.......",
      "....KvSSSSSSSSSSSSSSSSSSSSSSSSSSSSttttK......",
      "...KvvVSSSSSSSSSSSSSSSSSSSSSSSSSSSStttK......",
      "....KvvVVSSSSSSSSSSSSSSSSSSSSSSSSStttttK.....",
      "....KvvVVVVVVVSSSSSSSSSSSSSSSSSSStttttttK....",
      "...KvvSvvVVVVVSSSSSSSSSSSSSSSSSSutSttttttK...",
      "...KSSSSSSvvVvvSSSSSSSSSSSSuuuuSSSSSSStttK...",
      "..KSSSSSSSSvvvvvSSSSSSSSSuuuuuSSSSSSSSStttK..",
      "..KSSSSSSSSSvvvvvvvvSvvTvuuuuSSSSSSSSSSSttK..",
      ".KSSSSSSSSSvvvvvvvvvvvvvuuuuuuSSSSSSSSSttttK.",
      ".KuSSSSSSSvvvvvvvvvvvvvuuuuuuuuSSSSSSStttttK.",
      ".KtuuuSvvvvvvvvvvvvvvvuuuuuuuuuuuuSTuuuttttK.",
      ".KtuuuuuvvvvvvvvvvvvvuuuuuuuuuuuuuuuuuuttttK.",
      ".KtuuuuuuvuvuvvvuvuvuuuuuuuuuuuuuuuuuuutttttK",
      "KttuuuuuuuTTuuvuuuuuuuuuuuuuuuuuuuuuuuuuttttK",
      ".KtuuuuuuuTuuuuuuuuuuuuuuuuuuuuuuuuuuuuutttK.",
      ".KttuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuttttK.",
      ".KtttuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuttttK.",
      ".KttttuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuttttK.",
      ".KtttttuuuuuuuuuuuuuuuuuuuuuTTuuuuuututttttK.",
      ".KttttttuuuuuuuuuuuuuuuuuuuuTtutututtttttttK.",
      "KttttttttuuuuuuuuuuuuuuuuuuutttttttttttttttK.",
      "KtttttttttutuuuuuuuuuuuuututttttttttttttttK..",
      ".KtttttttttttututuuutututtttttttttttttttttK..",
      ".KTtttttttttttttttutttttttttttttttttttttTTK..",
      "..KTttttttttttttttttttttttttttttttttttTTKK...",
      "...KTTTTttttttttttttttttttttttttttttTTKK.....",
      "....KKKKTTtttttttttttttttttttttttttTKK.......",
      "........KKTTtttttttttttttttttttttTTK.........",
      "..........KKTTTtttttttttttttttTTTKK..........",
      "............KKKTTTTTTTtTTTTTTTKKK............",
      "...............KKKKTTTTTTKKKKK...............",
      "...................KwwTxK....................",
      "...................KwwwxK....................",
      "...................KwwwxK....................",
      "...................KwwwxK....................",
      "..................KwwwwxxK...................",
      "..................KwwwwxxK...................",
      "..................KwwwwxxK...................",
      "..................KwwwwxxK...................",
      "..................KwwwwxxK...................",
      "..................KwwwwxxK...................",
      "..................KwwwwxxK...................",
      "..................KwwwwxxK...................",
      "..................KwwwwxxK...................",
      "..................KwwwwxxK...................",
      "..................KwwwwxxK...................",
      ".................KwwwwwxxxK..................",
      ".................KwwwwwxxxK..................",
      ".................KwwwwwxxxK..................",
      ".................KwwwwwxxxK..................",
      ".................KwwwwwxxxK..................",
      ".................KKKKKKKKKK..................",
    ],
  },
  teamCar: {
    anchorCol: 50, anchorRow: 42,
    rows: [
      "....................................................K................................................",
      "..................................................KKWKK.........K....................................",
      "................................................KKWWWWWKK.....KKLKK..................................",
      "..............................................KKWWWWWWWWWKK.KKLLLLLKK................................",
      "............................................KKWWWWWWWWWWWWWKWLLLLLLLLKK..............................",
      "..........................................KKWWWWWWWWWWWWWWWWWWWLLLLLLLLKK............................",
      "........................................KKWWWWWWWWWWWWWWWWWWWWWWWLLLLLLLLKK..........................",
      "......................................KKWWWWWWWWWWWWWWWWWWWWWWWWWWWLLLLLLLLKK........................",
      "....................................KKWWWWWWWWWWWWWWWWWWWWGGWWWWWWWWWLLLLLLLLKK......................",
      "..................................KKWWWWWWWWWWWWWWWWrWWWGGWWWWWWWWWWWWWLLLLLLLLKK....................",
      "................................KKWWWWWWWWWWWWWWWrrrrrrrWWWWWWWWWWWWWWWWWLLLLLLLLKK..................",
      "..............................KKWWWWWWWWWWWWWWWWrrrrcrrrrWGGWWWWWWWWWWWWWWWLLLLLLLLKK................",
      "............................KKWWWWWWWWWWWWWWWWWWrrrcccrrrGWWWWWWWWWWWWWWWWWWWLLLLLLLLKK..............",
      "..........................KKWWWWWWWWWWWWWWWWWWWWrrrrcrrrrWWWWWWWWWWWWWWWWWWLLLLLLLLLLLLKK............",
      "........................KKWWWWWWWWWWWWWWWWWWWWGGWrrrrrrrWWWWWWWWWWWWWWWWWLgLLLLLLLLLLLLLLKK..........",
      "......................KKWWWWWWWWWWWWWWWWrWWWGGWWWWGGrWWWWWWWWWWWWWWWWWWLgggLLLLLLLLLLLLLLLLKK........",
      "....................KKWWWWWWWWWWWWWWWrrrrrrrWWWWGGWWWWWWWWWWWWWWWWWWWLLggggLLLLLLLLLLLLLLLLLLKK......",
      "..................KKWWWWWWWWWWWWWWWWrrrrcrrrrWGGWWWWWWWWWWWWWWWWWWWLLggggggLLLLLLLLLLLLLLLLLLLLKK....",
      "................KKWWWWWWWWWWWWWWWWWWrrrcccrrrGWWWWWWWWWWWWWWWWWWWLLggggggggLLLLLLLLLLLLLLLLLLLLLLKK..",
      "................KjWWWWWWWWWWWWWWWWWWrrrrcrrrrWWWWWWWWWWWWWWWWWWLLggggggggggLLLLLLLLLLLLLLLLLLLLLLLLKK",
      "................KjGjWWWWWWWWWWWWWWGGWrrrrrrrWWWWWWWWWWWWWWWWWLLLgggggggggggLLLLLLLLLLLLLLLLLLLLLLLLJK",
      "................KjGGGjWWWWWWWWWWGGWWWWGGrWWWWWWWWWWWWWWWWWWLLLgggggggggggggLLLLLLLLLLLLLLLLLLLLLLJJJK",
      "................KjGGGGjjWWWWWWWWWWWWGGWWWWWWWWWWWWWWWWWWWLLLgggggggggggggggLLLLLLLLLLLLLLLLLLLLJJJJJK",
      "................KjGGGGGGjjWWWWWWWWGGWWWWWWWWWWWWWWWWWWWLLLLgggggggggggggggLLLLLLLLLLLLLLLLLLLJJJJJJJK",
      "................KjGGGGGGGGjjWWWWGGWWWWWWWWWWWWWWWWWWWLLLLgLgggggggggggggLLLLLLLLLLLLLLLLLLLJJJJJJJJJK",
      "................KjGGGGGGGGGjjjWWWWWWWWWWWWWWWWWWWWWLLLLgggLggggggggggggLLLLLLLLLLLLLLLLLLJJJJJJJJJJJK",
      "..............KKjjGGGGGGGGGGGjjjWWWWWWWWWWWWWWWWWLLLLgggggLggggggggggLLLLLLLLLLLLLLLLLLJJJJJJJJJJJJJK",
      "............KKLLjjGGGGGGGGGGGGGjjjWWWWWWWWWWWWWLLLLLggggggLggggggggLLLLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJK",
      "..........KKLLLLjjGGGGGGGGGGGGGGjjjjWWWWWWWWWLLLLLggggggggLgggggggLLLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJK",
      "........KKLLLLLLjjjGGGGGGGGGGGGGGGjjjjWWWWWLLLLLggggggggggLgggggLLLLLLLLLLLLLLLLLJJJJJJJJJJJJJooooJJK",
      "......KKLLLLLLLLjjjjjGGGGGGGGGGGGGGGjjjjWLLLLLggggggggggggLgggLLLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJooWWJJK",
      "....KKLLLLLLLLLLjjjjjjGGGGGGGGGGGGGGGjjjLLLLLgggggggggggggLgLLLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJJK",
      "..KKLLLLLLLLLLLLLLjjjjjjGGGGGGGGGGGGGGGjLLLggggggggggggggggLLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJJJJK",
      "KKLLLLLLLLLLLLLLLLLLjjjjjjGGGGGGGGGGGGGjLLLggggggggggggggLLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJJJJJJK",
      "KjLLLLLLLLLLLLLLLLLLLLjjjjjGGGGGGGGGGGGjLLLggggggggggggLLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJJJJJJJJK",
      "KjjjLLLLLLLLLLLLLLLLLLLLjjjjjGGGGGGGGGGjLLLggggggggggLLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJJJJJJJJJKK",
      "KjjjjjLLLLLLLLLLLLLLLLLLLLjjjjjGGGGGGGGjLLLgggggggggLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJJJJJJJJJKK..",
      "KjjjjjjjLLLLLLLLLLLLLLLLLLLLjjjjGGGGGGGjLLLgggggggLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJJJJJJJJJKK....",
      "KjjjjjjjjjLLLLLLLLLLLLLLLLLLLLjjjjGGGGGjLLLgggggLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJJJJJJJJJKK......",
      "KjjjjjjjjjjjLLLLLLLLLLLLLLLLLLLLjjjjGGGjLLLggggLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJJJJJJJJJKK........",
      "KjjjjjjjjjjjjjLLLLLLLLLLLLLLLLLLLLjjjGGjLLLggLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJJJJJJJJJKK..........",
      "KjjjjjjjjjjjjjjjLLLLLLLLLLLLLLLLLLLLjjjjLLLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJJJJJJJJJKK............",
      "KjjjjjjjjjjjjjjjjjLLLLLLLLLLLLLLLLLLLLjjLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWrJJJJJJJJKK..............",
      "KjjjjjjjjjjjjjjjjjjjLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWrrrrrrJJJKK................",
      "KjjjjjjjjjjjjjjjjjjjjjLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWrrrrrrrrrJK..................",
      "KjjjjjjjjjjjjjjjjjjjjjjjLLLLLLLLLLLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJrrrrrrrrrrK...................",
      "KjjjjjjjjjjjjjjjjjjjjjjjjjLLLLLLLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJJJrrrrcccrrrK...................",
      "KjjjjjjjjjjjjjjjjjjjjjjjjjjjLLLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJJJJrrrrcccccrrrK..................",
      "KjjjjjjjjjjjjjjjjjjjjjjjjjjjjjLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJJJJJJJrrrrcccrrrK...................",
      "KKjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJJJJJJJJJKrrrrrrrrrK...................",
      "..KKjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjLLLLLJJJJJJJJJJJJJJJJJWWWWJJJJJJJJJKK.KrrrrrrrK....................",
      "....KKjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjLJJJJJJJJJJJJJJJJJWWWWJJJJJJJJJKK....KKKrKKK.....................",
      "......KKjjjjjjjjjjjjjjjjjjjjjjjjjjjjJJJJJJJJJJJJJJJJWWWWJJJJJJJJJKK.........K........................",
      "........KKjjjjjjjjjjjjjjjjjjjjjjjjjjJJJJJJJJJJJJJJWWWWJJJJJJJJJKK....................................",
      "..........KKjjjjjjjjjjjjjjjjjjjjjjjjJJJJJJJJJJJJWWWWJJJJJJJJJKK......................................",
      "............KKjjjjjjjjjjjjjjjjjjjjjjJJJJJJJJJJWWWWrrrrrJJJJKK........................................",
      "..............KKjjjjjjjjjjjjjjjjjjjjJJJJJJJJWWWWrrrrrrrrJKK..........................................",
      "................KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK............................................",
    ],
  },
};

// 金属・木・小物・車の静的パレット（K=輪郭）
export const OBJ_LEGEND = {
  K: "#1a1d22",
  a: "#454c55", b: "#647079", c: "#89959f", d: "#b4bfc8", // 金属（暗→明）
  r: "#23272d", R: "#3d444c", e: "#6a7683", // ドラム・タイヤ
  w: "#5c4426", x: "#7d5c33", y: "#9a7442", z: "#b8915a", i: "#33261a", // 木材・棚の内側
  1: "#c9463c", 4: "#e07a70", 2: "#4f8fe8", 5: "#8ab5f0", 3: "#e0a032", 6: "#f0c470", // 小箱
  J: "#2c55a8", j: "#24406f", L: "#3f74d4", M: "#5289e4", W: "#dfe6ee", g: "#9fc0e8", G: "#5f83b8", // 車体・窓
  o: "#f0d060", // ヘッドライト
};
