// 拠点画面の什器・プロップのドット絵データ（第19弾）。
// ローラー台・パーツ棚・工具箱・木＝ユーザー提供の参考画像からPillow抽出
// （scratchpad/w19/extract.py: 白背景除去→BOX縮小→adaptive量子化→despeckle。CLAUDE.md §6の系譜）。
// チームカー＝手描きlegend（参考画像は2台重なり＋ルーフの自転車が50px幅で潰れるため抽出不可）。
// 1セル=0.5スクリーンpx（PixelPersonの0.49と粒度統一）。anchorは接地点（足元中央）。
// 木の緑はt/u/v/V（季節パレットからpixelObject.jsxが動的に塗る）、S=冠雪（treeSnowのみ）。
// 各エントリのlegendはそのスプライト固有の静的色。無いもの（teamCar）はOBJ_LEGENDを使う。

export const OBJ_SPRITES = {
  rollerUnit: {
    anchorCol: 21, anchorRow: 24,
    legend: {"a":"#86a3a0","b":"#849696","c":"#6e726f","d":"#a9c8c5","e":"#c7e8e4","f":"#d6f5f2","g":"#b2d5d2","h":"#b7dad6","i":"#a5bbbd","j":"#908e82","k":"#9cb1b3","l":"#999792","m":"#9ba4a6"},
    rows: [
      ".............abc..........................",
      "...........adefg..........................",
      ".........adeffhhb.........................",
      ".......adeffhhgicjb.......................",
      ".....adeffhhgiaab.cbdek...................",
      "...bieffhhgiaacccadeffhb..................",
      "..ccdfhhgiaab..bieffhhgba.................",
      "..cccdhiaab..adeffhhgiacb.................",
      "mibjjlaab..aieffhhgiaabbbb................",
      "mbjikjjj.cbhffhhgiaab...jba...............",
      "mi..bikjjccbghgiaab.......jbb.............",
      "cjii..bimjjciiaab...........jbb...........",
      "...mii..limjjbb...............bbb....ak...",
      ".....mii..li.jj.................jbbagefhc.",
      ".......mii.m.....................bgefehhbl",
      ".........mimi..................mgefehhgkbm",
      "...........mii...............adefehhgkaaam",
      ".............mii...........bdefehhgkaa.cbb",
      "...............m..........ccdehhgkaa......",
      "..................i......jcccdgkaa........",
      "..................lmi....j.ccaaab.........",
      "....................lmi..bmdcab...........",
      "......................lmikiib.............",
      "........................lkiib.............",
      "..........................cmj.............",
    ],
  },
  partsShelf: {
    anchorCol: 24, anchorRow: 43,
    legend: {"a":"#1b1919","b":"#7f909b","c":"#b1b6b8","d":"#9c9e9d","e":"#75716e","f":"#838281","g":"#6e625b","h":"#575e6b","i":"#747e87","j":"#666f77","k":"#a28063","l":"#8b705d","m":"#a59281"},
    rows: [
      "..............................................aa",
      "..............................................aa",
      "........bccc..................................aa",
      "......bdcefccc................................aa",
      "....bccbfghidccd..............................aa",
      "...dccdgggehgjbdefbhgk........................aa",
      "...hdcfhhhehidjbgefggl........................aa",
      "..kldbccjhbbffeggllgici.......................aa",
      "elmkfdifbbibdjbbgglahjh.......................aa",
      "ielkmlfdddfdfgjigffhhkll......................aa",
      "jiiflkklfbfkmlmmgbdhhlgkejjjj.................aa",
      "jb..eelkmkmmmlbjhcmfjjhidhjiibi...............aa",
      "ji...hjflkmmmlijgccmklkhkiiibdi...............aa",
      "ji....bbiflkmmlklccfmkehfhjbbjjg..............aa",
      "jf..bcbiehiflkmmmlfllijjjjijidikk.............aa",
      "ji.ddjiijjjiielkmmmjmjjjibjiilkmlg............aa",
      "jbiciefejibbihielkmgliiidcilkkllgj............aa",
      "jigddciibbbihhhhielmkgjbblkmkgejhj............aa",
      "jelfdbcidijhijjjjiielkklkmklej...j............aa",
      "jjellbdibcbhjiibbihhiegklgej.....j............aa",
      "jiefelllbbibbbbijhhhhhhihjicb....j............aa",
      "jb..eigllfbibbbhhhjhjijbhggedcb.hj............aa",
      "jb....jfellfdhdcbhjibdjbhggggdd.hh............aa",
      "jb...bbhheelleijidibbigbhggebiig.j............aa",
      "ib.bbbhhaajfellfbdjdigebhefiiifkgj............aa",
      "jiidhhhahhjiifelffgbbcjbheifflkkgj............aa",
      "jiebcbhhibbbjhhfekkebijbjfflkkgghi............aa",
      "jildiibbbbhhhhhhiilklfjbjlkkggjjhj............aa",
      "jjglfbbjcbhhhhhibiifllgbhklgjh...j............aa",
      "jiffllfgbbcijibbbiijjigbjgeele...j............aa",
      ".ecbfelkfdiibdbjbbcijhjbhemmmml..j............aa",
      "...cdiiellfbdjcbbbjjkmedjmmmmkl..j............aa",
      ".....cdbfellefibbbemmmedhmmkkkl..j............aa",
      ".......ccffellebbdgkkmfdhkkkkklkgj............aa",
      ".........ccfiellfdgkkkedhkkkklkkgi............aa",
      "...........ccfiellllmlgdhklllmkghj............aa",
      ".............cdfiglklkedhglmkggjhj............aa",
      "..............ccdffekkgdjmkgejfcc.............aa",
      "................ccdifegdhggjfcc...............aa",
      "..................ccdijdjefcc.................aa",
      "....................ccfbjcc...................aa",
      ".......................ee.....................aa",
      "..............................................aa",
      "..............................................aa",
    ],
  },
  toolbox: {
    anchorCol: 22, anchorRow: 31,
    legend: {"a":"#998164","b":"#a58a6c","c":"#af9d89","d":"#9c7553","e":"#7b6a5c","f":"#62514c","g":"#906e54","h":"#924c46","i":"#bc4e46","j":"#9a332e","k":"#793331","l":"#b13932","m":"#b94138"},
    rows: [
      ".............................ab.............",
      "...........................accdbba..........",
      ".........................accaeefgbba........",
      "........................ccbdgfafeggbb.......",
      "............iiih......ccbagccefeefegeaa.ee..",
      "..........iiijkj....bbaaeeaccefeaffeeaebce..",
      ".......eeiijjljj...bbgeafcebaeeffaafikaccaa.",
      "......iihkjlmmjj...ddbaaccfefeaefeehifccecaa",
      "....iiijjlmmmmjjh..dgddbbffabceaeefihccccbda",
      "..hiijjlmmmmmmljh..dgfgdbcaeeaafcfefecbbbdaa",
      "hiijjlmmmmmmmmmjk..dggggddbbbbbbeefbcbbgggda",
      "kmkjmmmmmmmmmmmjj..gdggdgfgdbcefabcbbdgbagda",
      "kljmmmmmmmmmmmiik..gddddgggggdbcbaaggbbbbgda",
      "kjlmmmmmmmmmiihkhjkhdddggggdgfgbadgdbbbbbgda",
      ".jlmmmmmmmiihkimmjjjhgdgggddgggbadbabbbabgda",
      ".jlmmmmmiihkhijafkkjjjhggdgggdgbddbbadabbdda",
      ".kllmmiiikhmlleceefkkjjjhddggdgbddbddbbbbbga",
      ".kljiiikhimlhccffffeekklihgggggbddbbddbbbgec",
      ".kjmikhmjjgccffeffaefhiimhggddgbddbbbbagea..",
      "...hhhlhccceffeffffhimmmmhdddggbddbbbgea....",
      "...kmmjffcfhikfffhiimmmhhhagdbgaddadg.......",
      "...kjjllkfkjfffhiiehmhgekk..aggbdgea........",
      "...kjjjjlhkffhiimmkkgehahk...ceage..........",
      "...kjjjjjjlmmimmmmgefagjjk..................",
      "...kjjjjjjjlimmmgefeghmmhg..................",
      "...hjjjjjjjlilgefegjlmhg....................",
      "..cejjjjjjjlhefegjmmhg......................",
      "...cajjjjjjlhegjlmhg........................",
      ".....cgjjjjljjmmmg..........................",
      ".......chjjllllg............................",
      ".........cgjihb.............................",
      "...........cb...............................",
    ],
  },
  tree: {
    anchorCol: 23, anchorRow: 58,
    legend: {"c":"#4e5a34","m":"#c9cfc1"},
    rows: [
      ".....................tuuc.....................",
      ".................ttuuvVVVuutt.................",
      "................tVVVVVVVVVVVVt................",
      "..............utvVVVVVVVVVVVVvt...............",
      ".............utvVVVVVVVVVVVVVVvtt.............",
      "............cuvvVVVVVVVVVVVVVVvvvt............",
      "............tuvvvVVVVVVVVVVVVvvvut............",
      "...........tuvvvvvVVVVVVVVVVVvvvutt...........",
      "...........vvvVvvvVVvVVVVVVvvvuuuuu...........",
      "...........tvvVvVVvvvVVvvvvvvvtuuut...........",
      "..........tuuvvvVVvVvvvvvvvuvvuvvuut..........",
      "..........tttuvvvvVVvvvvvvttuuuuuuut..........",
      ".........utttuuuvvvvvvvvvvvvvvvuuuttu.........",
      "........uuVtuuuuvuvvvvvvvvvvuuuuuutVtu........",
      ".......uVVVuttutttuuuuvvuuuuuuuuttuVVVu.......",
      "......ttVVVVvttuttttuuuuuuuuuuuutuVVVVtt......",
      ".....uuvVVVVVuttttttuuuuuuttttttuvVVVVvu......",
      ".....tuvvVVVVVvvvvuvttutttuuuvvVVVVVVvvuc.....",
      ".....tuvvvVVVVVvvvVvvuuuvvvvvvVVVVVVvvvut.....",
      "....tuvvvvVVVVVVVVVVvvvvvvVVVVVVVVVVvvuttt....",
      "....tvvvvvVVVVVVVVVVVVVVVVVVVVVVVVVVvvuttc....",
      ".....tuvvvvvvVvVVVVVVVVVVVvvVVVVVvvvvvutt.....",
      ".....ttuuvvvvvvvvvVVVVVVVVvvvvvvvvvvuuttt.....",
      ".....tttvvvvvvvvvvvvvVVvvvvvvvtvvvvvttttt.....",
      "....tttuvvuvvuvvvvvvvvvvvvvvtttuuuuuuvutt.....",
      "....tuttttttttvvvvvvvvvvvvvuututttttuvutvt....",
      "..utvvtttttttttutvvvvvvvvuuuuututtttttttvut...",
      "..tuvvvttttttttttuuuuuuuuuuttttttttttttvvuut..",
      "..tuvvvttttttttutuuttttuututttttttttttuvvutt..",
      ".tuuuvvuuutttttttttuttttttttttttttttuuvvvuttt.",
      ".tuuuuvvvuuuttttttttttttttttttttttuuvvvvvuttt.",
      "cttttuvvvvvuuuuuttttttttttttutuuuuuvvvvutttttt",
      "ctttttuvvvvvuuuuuuuuuuttuuuuuuvuuuvvvvvttttttt",
      ".tttttuvvvvvvvvvvuuuuuuuuuuuuuvvvvvvvvttttttt.",
      "tttttuutuvvvvvvvvvvvvvvuuvvvvuuvuvvtvvuttttttc",
      "ttuttttuuuuttvvvvvvvvvvvvvvvuttutttttttttttttt",
      ".ttttttutttttuutuuvvvvvvvvvvutttttttttttttttt.",
      ".tttuuuutttttttttuvuvvvvvvtuttttttttttttttttt.",
      ".tttttttttttttutttttuvuuvvttttttttttttttuttt..",
      "..ttttttttttttuttttttttttttttttttttttttutttt..",
      "...ttttttuutuuuutttttttttttttttuttttttttttc...",
      "...ttttttttttuuttttttttttttutttttttttttttt....",
      ".....ttttttttttttttttttttttttttttttttttt......",
      ".......tttttttttttttttttttttttttttttttt.......",
      "..........ttcttttttttttttttttttttttt..........",
      "............ctttttttctttttttttttt.............",
      ".................ttcccccccct..................",
      "..............................................",
      "..............................................",
      "..............................................",
      "..............................................",
      "..............................................",
      "..............................................",
      "..............................................",
      "..............................................",
      "..............................................",
      "..............................................",
      "..............................................",
      "..............................................",
    ],
  },
  treeSnow: {
    anchorCol: 23, anchorRow: 58,
    legend: {"c":"#4e5a34","m":"#c9cfc1"},
    rows: [
      ".....................SSSc.....................",
      ".................SSSSvSSSSSSS.................",
      "................SSVSSVVVVSSVSS................",
      "..............SSSVVVVVVVVVVVVSS...............",
      ".............SSvVVVVVVVVVVVVVVvSS.............",
      "............cSvvVVVVVVVVVVVVVVvSSS............",
      "............SuvvvVVVVVVVVVVVVvvvut............",
      "...........SuvvvvvVVVVVVVVVVVvvvutS...........",
      "...........SvvVvvvVVvVVVVVVvvvuuuuS...........",
      "...........tvvVvVVvvvVVvvvvvvvtuuut...........",
      "..........SuuvvvVVvVvvvvvvvuvvuvvuuS..........",
      "..........SttuvvvvVVvvvvvvttuuuuuuuS..........",
      ".........StttuuuvvvvvvvvvvvvvvvuuuttS.........",
      "........SuVtuuuuvuvvvvvvvvvvuuuuuutVtS........",
      ".......SSVVuttutttuuuuvvuuuuuuuuttuVVSS.......",
      "......SSVVVVvttuttttuuuuuuuuuuuutuVVVVSS......",
      ".....SuvVVVVVuttttttuuuuuuttttttuvVVVVvu......",
      ".....SuvvVVVVVvvvvuvttutttuuuvvVVVVVVvvuc.....",
      ".....tuvvvVVVVVvvvVvvuuuvvvvvvVVVVVVvvvuS.....",
      "....SuvvvvVVVVVVVVVVvvvvvvVVVVVVVVVVvvutSS....",
      "....SvvvvvVVVVVVVVVVVVVVVVVVVVVVVVVVvvuttc....",
      ".....tuvvvvvvVvVVVVVVVVVVVvvVVVVVvvvvvutt.....",
      ".....ttuuvvvvvvvvvVVVVVVVVvvvvvvvvvvuuttt.....",
      ".....tttvvvvvvvvvvvvvVVvvvvvvvtvvvvvttttt.....",
      "....tttuvvuvvuvvvvvvvvvvvvvvtttuuuuuuvutt.....",
      "....tuttttttttvvvvvvvvvvvvvuututttttuvutvt....",
      "..SSvvtttttttttutvvvvvvvvuuuuututtttttttvuS...",
      "..SuvvvttttttttttuuuuuuuuuuttttttttttttvvuuS..",
      "..tuvvvttttttttutuuttttuututttttttttttuvvutS..",
      ".SuuuvvuuutttttttttuttttttttttttttttuuvvvuttS.",
      ".SuuuuvvvuuuttttttttttttttttttttttuuvvvvvuttS.",
      "cttttuvvvvvuuuuuttttttttttttutuuuuuvvvvutttttS",
      "ctttttuvvvvvuuuuuuuuuuttuuuuuuvuuuvvvvvttttttt",
      ".tttttuvvvvvvvvvvuuuuuuuuuuuuuvvvvvvvvttttttt.",
      "Sttttuutuvvvvvvvvvvvvvvuuvvvvuuvuvvtvvuttttttc",
      "ttuttttuuuuttvvvvvvvvvvvvvvvuttutttttttttttttt",
      ".ttttttutttttuutuuvvvvvvvvvvutttttttttttttttt.",
      ".tttuuuutttttttttuvuvvvvvvtuttttttttttttttttt.",
      ".tttttttttttttutttttuvuuvvttttttttttttttuttt..",
      "..ttttttttttttuttttttttttttttttttttttttutttt..",
      "...ttttttuutuuuutttttttttttttttuttttttttttc...",
      "...ttttttttttuuttttttttttttutttttttttttttt....",
      ".....ttttttttttttttttttttttttttttttttttt......",
      ".......tttttttttttttttttttttttttttttttt.......",
      "..........ttcttttttttttttttttttttttt..........",
      "............ctttttttctttttttttttt.............",
      ".................ttcccccccct..................",
      "..............................................",
      "..............................................",
      "..............................................",
      "..............................................",
      "..............................................",
      "..............................................",
      "..............................................",
      "..............................................",
      "..............................................",
      "..............................................",
      "..............................................",
      "..............................................",
    ],
  },
  teamCar: {
    anchorCol: 50, anchorRow: 42,
    rows: [
      "....................................................K................................................",
      "..................................................KKWKK.........K....................................",
      "................................................KKWWWWWKK.....KKLKK..................................",
      "..............................................KKWWWWWWWWWKK.KKLLLLLKK................................",
      "............................................KKWWWWWWWWWWWWWKWLLLLLLLLKK..............................",
      "..........................................KKWWWWWWWWWWWWWWWWWWWLLLLLLLLKK............................",
      "........................................KKWWWWWWWWWWWWWWWWWWWWWWWLLLLLLLLKK..........................",
      "......................................KKWWWWWWWWWWWWWWWWWWWWWWWWWWWLLLLLLLLKK........................",
      "....................................KKWWWWWWWWWWWWWWWWWWWWGGWWWWWWWWWLLLLLLLLKK......................",
      "..................................KKWWWWWWWWWWWWWWWWrWWWGGWWWWWWWWWWWWWLLLLLLLLKK....................",
      "................................KKWWWWWWWWWWWWWWWrrrrrrrWWWWWWWWWWWWWWWWWLLLLLLLLKK..................",
      "..............................KKWWWWWWWWWWWWWWWWrrrrcrrrrWGGWWWWWWWWWWWWWWWLLLLLLLLKK................",
      "............................KKWWWWWWWWWWWWWWWWWWrrrcccrrrGWWWWWWWWWWWWWWWWWWWLLLLLLLLKK..............",
      "..........................KKWWWWWWWWWWWWWWWWWWWWrrrrcrrrrWWWWWWWWWWWWWWWWWWLLLLLLLLLLLLKK............",
      "........................KKWWWWWWWWWWWWWWWWWWWWGGWrrrrrrrWWWWWWWWWWWWWWWWWLgLLLLLLLLLLLLLLKK..........",
      "......................KKWWWWWWWWWWWWWWWWrWWWGGWWWWGGrWWWWWWWWWWWWWWWWWWLgggLLLLLLLLLLLLLLLLKK........",
      "....................KKWWWWWWWWWWWWWWWrrrrrrrWWWWGGWWWWWWWWWWWWWWWWWWWLLggggLLLLLLLLLLLLLLLLLLKK......",
      "..................KKWWWWWWWWWWWWWWWWrrrrcrrrrWGGWWWWWWWWWWWWWWWWWWWLLggggggLLLLLLLLLLLLLLLLLLLLKK....",
      "................KKWWWWWWWWWWWWWWWWWWrrrcccrrrGWWWWWWWWWWWWWWWWWWWLLggggggggLLLLLLLLLLLLLLLLLLLLLLKK..",
      "................KjWWWWWWWWWWWWWWWWWWrrrrcrrrrWWWWWWWWWWWWWWWWWWLLggggggggggLLLLLLLLLLLLLLLLLLLLLLLLKK",
      "................KjGjWWWWWWWWWWWWWWGGWrrrrrrrWWWWWWWWWWWWWWWWWLLLgggggggggggLLLLLLLLLLLLLLLLLLLLLLLLJK",
      "................KjGGGjWWWWWWWWWWGGWWWWGGrWWWWWWWWWWWWWWWWWWLLLgggggggggggggLLLLLLLLLLLLLLLLLLLLLLJJJK",
      "................KjGGGGjjWWWWWWWWWWWWGGWWWWWWWWWWWWWWWWWWWLLLgggggggggggggggLLLLLLLLLLLLLLLLLLLLJJJJJK",
      "................KjGGGGGGjjWWWWWWWWGGWWWWWWWWWWWWWWWWWWWLLLLgggggggggggggggLLLLLLLLLLLLLLLLLLLJJJJJJJK",
      "................KjGGGGGGGGjjWWWWGGWWWWWWWWWWWWWWWWWWWLLLLgLgggggggggggggLLLLLLLLLLLLLLLLLLLJJJJJJJJJK",
      "................KjGGGGGGGGGjjjWWWWWWWWWWWWWWWWWWWWWLLLLgggLggggggggggggLLLLLLLLLLLLLLLLLLJJJJJJJJJJJK",
      "..............KKjjGGGGGGGGGGGjjjWWWWWWWWWWWWWWWWWLLLLgggggLggggggggggLLLLLLLLLLLLLLLLLLJJJJJJJJJJJJJK",
      "............KKLLjjGGGGGGGGGGGGGjjjWWWWWWWWWWWWWLLLLLggggggLggggggggLLLLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJK",
      "..........KKLLLLjjGGGGGGGGGGGGGGjjjjWWWWWWWWWLLLLLggggggggLgggggggLLLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJK",
      "........KKLLLLLLjjjGGGGGGGGGGGGGGGjjjjWWWWWLLLLLggggggggggLgggggLLLLLLLLLLLLLLLLLJJJJJJJJJJJJJooooJJK",
      "......KKLLLLLLLLjjjjjGGGGGGGGGGGGGGGjjjjWLLLLLggggggggggggLgggLLLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJooWWJJK",
      "....KKLLLLLLLLLLjjjjjjGGGGGGGGGGGGGGGjjjLLLLLgggggggggggggLgLLLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJJK",
      "..KKLLLLLLLLLLLLLLjjjjjjGGGGGGGGGGGGGGGjLLLggggggggggggggggLLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJJJJK",
      "KKLLLLLLLLLLLLLLLLLLjjjjjjGGGGGGGGGGGGGjLLLggggggggggggggLLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJJJJJJK",
      "KjLLLLLLLLLLLLLLLLLLLLjjjjjGGGGGGGGGGGGjLLLggggggggggggLLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJJJJJJJJK",
      "KjjjLLLLLLLLLLLLLLLLLLLLjjjjjGGGGGGGGGGjLLLggggggggggLLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJJJJJJJJJKK",
      "KjjjjjLLLLLLLLLLLLLLLLLLLLjjjjjGGGGGGGGjLLLgggggggggLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJJJJJJJJJKK..",
      "KjjjjjjjLLLLLLLLLLLLLLLLLLLLjjjjGGGGGGGjLLLgggggggLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJJJJJJJJJKK....",
      "KjjjjjjjjjLLLLLLLLLLLLLLLLLLLLjjjjGGGGGjLLLgggggLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJJJJJJJJJKK......",
      "KjjjjjjjjjjjLLLLLLLLLLLLLLLLLLLLjjjjGGGjLLLggggLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJJJJJJJJJKK........",
      "KjjjjjjjjjjjjjLLLLLLLLLLLLLLLLLLLLjjjGGjLLLggLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJJJJJJJJJKK..........",
      "KjjjjjjjjjjjjjjjLLLLLLLLLLLLLLLLLLLLjjjjLLLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJJJJJJJJJKK............",
      "KjjjjjjjjjjjjjjjjjLLLLLLLLLLLLLLLLLLLLjjLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWrJJJJJJJJKK..............",
      "KjjjjjjjjjjjjjjjjjjjLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWrrrrrrJJJKK................",
      "KjjjjjjjjjjjjjjjjjjjjjLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWrrrrrrrrrJK..................",
      "KjjjjjjjjjjjjjjjjjjjjjjjLLLLLLLLLLLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJrrrrrrrrrrK...................",
      "KjjjjjjjjjjjjjjjjjjjjjjjjjLLLLLLLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJJJrrrrcccrrrK...................",
      "KjjjjjjjjjjjjjjjjjjjjjjjjjjjLLLLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJJJJrrrrcccccrrrK..................",
      "KjjjjjjjjjjjjjjjjjjjjjjjjjjjjjLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJJJJJJJrrrrcccrrrK...................",
      "KKjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjLLLLLLLLLJJJJJJJJJJJJJJJJJWWWWJJJJJJJJJKrrrrrrrrrK...................",
      "..KKjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjLLLLLJJJJJJJJJJJJJJJJJWWWWJJJJJJJJJKK.KrrrrrrrK....................",
      "....KKjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjLJJJJJJJJJJJJJJJJJWWWWJJJJJJJJJKK....KKKrKKK.....................",
      "......KKjjjjjjjjjjjjjjjjjjjjjjjjjjjjJJJJJJJJJJJJJJJJWWWWJJJJJJJJJKK.........K........................",
      "........KKjjjjjjjjjjjjjjjjjjjjjjjjjjJJJJJJJJJJJJJJWWWWJJJJJJJJJKK....................................",
      "..........KKjjjjjjjjjjjjjjjjjjjjjjjjJJJJJJJJJJJJWWWWJJJJJJJJJKK......................................",
      "............KKjjjjjjjjjjjjjjjjjjjjjjJJJJJJJJJJWWWWrrrrrJJJJKK........................................",
      "..............KKjjjjjjjjjjjjjjjjjjjjJJJJJJJJWWWWrrrrrrrrJKK..........................................",
      "................KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK............................................",
    ],
  },
};

// チームカー等・手描きスプライトの共通パレット（K=輪郭）
export const OBJ_LEGEND = {
  K: "#1a1d22",
  a: "#454c55", b: "#647079", c: "#89959f", d: "#b4bfc8", // 金属（暗→明）
  r: "#23272d", R: "#3d444c", e: "#6a7683", // ドラム・タイヤ
  w: "#5c4426", x: "#7d5c33", y: "#9a7442", z: "#b8915a", i: "#33261a", // 木材
  1: "#c9463c", 4: "#e07a70", 2: "#4f8fe8", 5: "#8ab5f0", 3: "#e0a032", 6: "#f0c470", // 小箱
  J: "#2c55a8", j: "#24406f", L: "#3f74d4", M: "#5289e4", W: "#dfe6ee", g: "#9fc0e8", G: "#5f83b8", // 車体・窓
  o: "#f0d060", // ヘッドライト
};
