// 自転車に乗った選手のドット絵モデル（Wave G-1改）。
//
// 【解像度を揃えた経緯・重要】
// 最初に受け取った自転車の参考画像は58×80マス相当で描かれており、人物(16×36)と並べると
// 1マスの実寸が2.2倍違って「人物はカクカク、自転車は滑らか」というチグハグな絵になった
// （粒度差はまさに"安っぽさ"の原因になるため看過できない）。低解像度へ落として揃えようと
// したが、22×30/29×40では自転車の形が判別不能まで潰れた。そこでユーザーに粗い粒度で
// 参考画像を描き直してもらい、人物と同じ「1マス≒6px」の絵として取り直したのが本データ。
// 人物側(pixelPerson.jsx)は16×36のまま変更していない。
//
// 抽出は scratchpad のPillowスクリプトで実施：背景を透明化 → 面積平均(BOX)で縮小 →
// アルファを閾値30で二値化（車輪のスポークが細く、閾値が高いと車輪が輪だけになって
// 穴が空く）→ 連結成分の最大だけ残す（ラベル等の混入を落とす）→ パレットへ最近傍写像。
//
// 参考画像は輪郭ドットを含むため、`pixelSprite`の自動縁取りは false で呼ぶこと。
import React from "react";
import { pixelSprite, shade } from "./kit.jsx";

// legend文字：K=輪郭 D=タイヤ M=中間グレー R=スポーク/リム W=ハイライト
//              J=ジャージ/フレーム(動的・チーム色) j=その陰
//              S=肌 s=肌の陰 H=髪
// ※フレームとジャージを同じ動的色にしてある。ロードレースではチームカラーの車体が
//   普通なので、選手ごとに車体色も変わるのはむしろ自然。
const BIKE = {
  normal_SE: [
    ".....................................",
    ".....................................",
    "..............KKKKKD.................",
    "............DDjMjjjDKM...............",
    "...........DjJJJJJJjjD...............",
    ".........MMDMJJJJJjjjjD..............",
    ".........KDDJJJJJJJjjjK..............",
    ".........KRMMRRRRJjjjjK..............",
    ".........DKKHHHKKKHKKKK..............",
    "...........HssSsMSsHHHK..............",
    "...........DsHSSHSsHsHK..............",
    "...........HSsSSMSSsSHD..............",
    "...........HsSSSSSSsDD...............",
    "...........DsSssSSsHKM...............",
    "............DsSSSsHKjKK..............",
    ".............KKKKKMJJJJKM............",
    ".............DJJjjJJJJJjD............",
    "............HJjjJJJjJJJJDM...........",
    "...........MDjjDjJjDJJjJJK...........",
    "...........DRDDDDJDKjJKJJDM..........",
    "..........DsSsKMDDKMMDKJJjD..........",
    ".........DsSSMM..MHSSHjJJjD..........",
    "........HsSSHD...DsSsKjjJJDD.........",
    "....DKMHsSsHDM..DsSSHjjJjKKD.........",
    "...HDHDSsKKM...DMSSMKKKKKKKD.........",
    "...HDDKsHHMKKDKDSSMKKKKHHHKD.........",
    "...KHKDDDKDDDKSSSHKKKKHHKKKD.........",
    "...DMKHM..DDKKsSMKKKHHHKKKDM.........",
    "....MKHK..DJKKDDKsKHHHHKKD..MMM......",
    "......DD..KRKHDMMsHSSDKKKRDDKKKDDM...",
    ".........DDJKKKDDDHSSsKjDMKKDDDDKD...",
    "......DKHKDJKJDDDDKsSsKJjKKHDDDDDKD..",
    "....MDKHDHKRKjMMDMHMSSKjKjKM...DDDD..",
    "...MDHDKKKKRKKjMDHsHSSKDKDjD....DDDD.",
    "...DKDHDKDMDDKMjRKHKsRKKKKjJD....DDH.",
    "..DHDK..DDMDKDDDjRKKKKKKHDDjjK...DDH.",
    "..DDK...DDRDDDKMDJMKHHKKKHDKJjD..DDD.",
    ".MDDD..DDMMDRKKD.DKKHKDKDjjjjDD..DDH.",
    ".DDD...DDMjDMDDD.DKHKDMKDKKKKD..MDDH.",
    ".DDD..MHDMD..DDD.DKKHDKKKDRMD...DDHM.",
    ".DDH...DDDM..DHD.DKKKKDKHDRMM..MDDD..",
    ".DDH....MM..DDKD.KKKKD.DKDD...MDDHD..",
    ".DKDM.......DDHM.DDDD...DHDDDDDDKD...",
    ".MDDD......MDHK.........MHKDDDDKHM...",
    "..DHDD.....DDHM..........MDKKKKMM....",
    "..MDDDDMDMKDHD.............M.........",
    "...MKKDDDDDKD........................",
    "....MKKDDHDD.........................",
    "......DDDD...........................",
    ".....................................",
  ],
  normal_NE: [
    ".................................",
    ".................................",
    "................DKKKKM...........",
    "...............KDjjMMjKM.........",
    "..............KjjJJJJJRDM........",
    ".............KjjjjjJJJJDDD.......",
    ".............KjjjjjjJJJJMDK......",
    ".............KjKjjjjJJMDDDK......",
    ".............KDjjDDKKKHKMM.......",
    ".............KKKKKKHMKSHM........",
    ".............KHHHHHMSKSHM........",
    ".............MKHHHHHSMSDM........",
    "..............MKHHHssSSHM........",
    ".............DDKKKMsSSsD.........",
    "...........DDjJJJjDKHMD..........",
    "..........MDJJJJJJJJDKM..........",
    "..........DJJJJJJJJJJDD..........",
    ".........DjJJJJJJJjJJJDM.........",
    "........MDjJJJJJJJKjJJDD.........",
    "........DjJJJJJJJJDKjjDDM........",
    "........DjJJJJJJJjDDKMSsDM.......",
    ".......MjJJJJJJJjDD.MHsSSMHMDD...",
    ".......DjjJJJJJJjD..MDKsSSSHKDH..",
    ".......DKKKKKjJjDD.DKDDKKsSsKDK..",
    ".......DKKHHKKKKKD.DHKKKHKHKKKH..",
    ".......MKKKHHHHHKKDMDDjDM..MKMK..",
    "........DKKKKKHHHHKKjJJDM.DHD.D..",
    "........KKKKKKKHHHHKDKjMD.MDM....",
    ".........MKKDKKKKKDDDMjRDDDHD....",
    "..........KDJjjKKMssKRKJDKDDKD...",
    ".........MDDJKMsHsSsKMKKRKHHDHD..",
    ".....MDHDHDMDjMsKSSDJKHKRDMMDDH..",
    "....MHDDDKKRKRDMHSSKKKKDjMD.MDDD.",
    "...MKHDKKKDJKMKKMSMKKHDDDRK..HDK.",
    "...HDDDRDKRKKjMKKRHMKDD.HMD..DDH.",
    "..DHDD.DjMMKKKMKHKKRKDM.KDDM.MDH.",
    "..HDK..DDMjMKKDKHDKDKDD.MKD..DDK.",
    ".DHDM..DDJDKKKKDHKDKKDD......DDK.",
    ".DDHM.DDDjDDjjKDMDKKKHD.....MDHM.",
    ".DDH..KDjjjDKKKDKDDMMKH.....DDH..",
    ".DHK...HDKMMHKKDMDD.MKHHM.MDDDM..",
    ".DDH....DDRMHK.DKD...MKDDHDDKD...",
    ".DKDM...MDMHDD........DDKDHDD....",
    "..DDDM...MDDKM..........DDDM.....",
    "..DKDD..MDDHM....................",
    "...DKDDDDDKKD....................",
    "....DHHDHHD......................",
    ".....MDDDM.......................",
    ".................................",
  ],
  dancing_SE: [
    "...................................",
    "...................................",
    "...........DHHKHD..................",
    ".........MKjMjjjDH.................",
    ".........DMJJJJJjjD................",
    ".........DJJJJJjjjK................",
    "......MKDJMJJJJjjjjK...............",
    "......DDMMMRRMJjjjjK...............",
    "......MDDKKKKKKHKKKK...............",
    ".........HssSsSsHHHK...............",
    "........MHMsSDSsHsHK...............",
    ".........HsSSsSSsSHM...............",
    ".........HSSSSSSsHKM...............",
    ".........DsssSSSHDJjH..............",
    ".........MDssssKDjJJJKM............",
    "..........MKKKKMjjJJJJDM...........",
    "..........DjjjjJJjJJJJJD...........",
    ".........MDJjDJJjjJJjjJjD..........",
    ".........DKjjDDJjKDKDjJJK..........",
    ".........DMDKDMDjMSsKjJJjD.........",
    ".........DSSDM.MKMSsDjJJjK.........",
    "........MMSsD..MHSSDjjjJJDM........",
    ".......MDSsD...MMSsKjjjjDKM........",
    ".....MMDSsMM...HSSHDjjKKKKM........",
    "....DHHssDM..DDDSsKKKKKHHKM........",
    "...MKDHsKKDDHKMSSDKKKKHHKKM........",
    "...MKDHHKKMDDKsSsKKKKHHKKM.........",
    "...MKKHMMMDHKKHHHKKKHHHKK..........",
    "...MHDDD..DMDDMMMHKKKKHKDD.........",
    "....DMHKDMDJDKD.DMMDSsHHHD.........",
    "......DHDMDJjjjDDDMDSSMKD.MDDHM....",
    ".........DMjjKDDjjjHSSsH.MDKKKDM...",
    "......DHDKjMjMMRDHHKsSSHMKHDDDKD...",
    "....MDHDDKDMKJMDMMsMHsSMDKHDDDHHD..",
    "....DHDDHKDJKKJMMDssKHSSDDD...DDD..",
    "...DHDDDKjDDHKKJMMMsDDMRKKDM...DDD.",
    "..MHDD..DDMMDKMDRMHKJDKKHKjDM..DDD.",
    "..DDK...jDMMDDKMDRKKJKKHHKDjKM.DDD.",
    "..DDD..MjMjMDDK.DDJKJKKKDDDjD..DDD.",
    ".HDDM..DDRD.DDK..DDDDKKDMDjDK..DDD.",
    ".HDD..MDDMD.MDK..DDDKKHDKKKDM..DDD.",
    ".HDD...DDDM.MDK.MHDDDHKKKRM...MDKM.",
    ".HHD........DDK.DHKKKMDHDM....DDH..",
    ".HKDM.......DKM.KKKKM..KDD...DDK...",
    "..DDD......DDKM........DKDDDDDKK...",
    "..DDDM....MDHD..........DKDDDKD....",
    "..MKDDM..MDDKD............HHHM.....",
    "...DKDDDDDDHM......................",
    "....DKHDDHKM.......................",
    "......DDDD.........................",
    "...................................",
  ],
  dancing_NE: [
    "..................................",
    "..................................",
    "...........DKKKDD.................",
    "..........DMMjjjDD................",
    ".........HMJJJjjjjD...............",
    "........MDJJJjjjjjDD..............",
    ".......DMMJJJjjjjjDH..............",
    ".......DDDJJJjjjKKDH..............",
    ".......MMKHKjjjjjjDH..............",
    "........MKsHHKKKKKKD..............",
    "........MHsMsHHHHHHD..............",
    "........MHSssHHHHKM...............",
    ".........DsSsDKKKKDD..............",
    ".........MDSMDjjjjjjKM............",
    "..........MHDJJJJJJJJDM...........",
    "...........DJJJJJJ....D...........",
    "..........HJJJJJ......DM..........",
    ".........MDJJjjJ..JJJJJK..........",
    ".........DjJJDjJ.JJJJJJDD.........",
    ".........DDDjDDJJJJJJJJjK.........",
    "........MDSsKMDjJRJJJJJJDM........",
    "........DSSsK.MKjJJJJJJJjD........",
    ".......DsSsH...KjJJDKKKKKD........",
    "...MKMHMSsHMM..KKKKKHHHHKD........",
    "...KDKSsHKHKHDHKHHHHHHKHKD........",
    "...KDKMDKDDHKHHKHHHHKKKKKM........",
    "...KKKDDMMDKHMHKHHHHKKKKD.........",
    "...KDHD..DJDDDKKHHKKKKKKM.........",
    "...DMDHD.DJjJDMHKHKKKDDDK.........",
    ".....MDMDDJKDKsSsHKMKKKKD.........",
    ".....DKHKJDRDMsSSHjMKMK...........",
    "...MDHDDKRDjMMMSSMKHjjD.MMMM......",
    "...KHDKKDMDKMMDsSSHMjMKDDKHDDM....",
    "..DHDD.DMDKKDMMDSSMDjDDKDDDDKDM...",
    "..KDHM.DMDKDKjMKMSMDDKMKKDDDDKD...",
    ".DDD...DMKDDKKMMKHDKKKDMD...DDKM..",
    ".KDD...DMK.KKDDJKKHHKKKJD....DDK..",
    ".KMD..DRDD.KDKMKKDHKKDDDMD...HDK..",
    ".KDD..KjKM.KDDRKHHKMKDDDRKK...DDD.",
    ".KDD..MDM..KDDMKDHDDKKKKDjDK..DDK.",
    ".DDD.......KDDMKKDDDDjRMJJDK..HDH.",
    "..KDD.....MDHM.DKKDKKKKDKKKM..DDH.",
    "..DDDM....HDK..DKKKMDDH.MHM...DDH.",
    "...KDDMM.DDKD...MMM.DHD..M...MDKM.",
    "...MKDDDDDHK.........DMD.....DDK..",
    "....MHHDDHH..........HDDD...DDK...",
    "......DDDM............DHDDDDDKD...",
    ".......................DDDDDHH....",
    "........................MKKKD.....",
    "..................................",
  ],
  sprint_SE: [
    "........................................",
    "........................................",
    "..........MDDDDDM.......................",
    ".........MDMMMjjDD......................",
    "........MDJJJJJJjjD.....................",
    "........DJJJJJJjjjDM....................",
    "......DDDJJJJJJjjjjD....................",
    "......KJRRMJJJJjjjDDMMDMM...............",
    "......DDDDMMMMjDjDKKjjjjDKD.............",
    "........HMHHHHMHHHKDJJJJJjDD............",
    "........HsMSMsSMHDHDJJJJJJJjD...........",
    "........DsMSMsSMsMKjJJJJJJJJjD..........",
    "........DSSSSSSSSMDJJJjJJJJJjDM.........",
    "........DsSSSSSSMDJJJJjKJJJJJKM.........",
    "........MDSsSSsMDJjJJJDjjjjJDKKM........",
    ".........DHMMDHDjjKJJJKjjjjKKKKM........",
    ".........DDDjKKDjjKKDjKjjKKKKKKM........",
    "........MDSsDK.MDKKssDKKKKKHHKKDD.......",
    "..MHDDDDDSSsD....MHSSDKKKHHHKKHDD.......",
    "..HDHKDDSSsHM...MKMSsHKKHKKHKKDD........",
    "..KHKDsMDHHKKHKKDMSSMKKKHHKKKKM.........",
    "..HKHHDHKDHDKDssSSSsHKHHKHKKHD..........",
    "..HKSHKD..HKKsSSMDDHKKSSDKKKD...........",
    "..DKMMD...KMKsSMKKDDKDSSSKDKMMDKKDM.....",
    "...MDD...MKMDKKDMKsMHDSSsKJKDKDDDDKDM...",
    ".......DDHKMjDMD.HsSMHSSDDjMKHHDDDDHD...",
    ".....KHDDDKMjKMMMDHSsHSSMjDJMKM..MDDHD..",
    "....DHDDHKKMjKKRDRDMsHSSMjKKRD....MDDH..",
    "...DDDHMMDDRDDKKMMMHsHSSMDKDDJD....MDDD.",
    "..MKDD...DMMDDDKDMMDKKSSDKKHDDjKM...DDD.",
    "..DDD...MjMDMDDKDDMDKKHDKKDDDKjDKM..DDD.",
    ".MDDD...DjMD.MHDKMDJDKKKKKKKHKKJDM..DDD.",
    ".DDH....KMMM..KDK.DKKKKKKKjMRRMjKM..DDD.",
    ".DDH...KDMD...KDK..KDDHDMDjDKKKKD...HDD.",
    ".DDH...DDMD...KDK.DKKKMDKKKH..DM...DDKM.",
    ".DDH....MDM...HDK.MDKKKKDKKHM.M...MHDK..",
    ".DHDM........DDKD...DKKDM.KDD.....DDKM..",
    ".MKDD........HDK.....MM...KHDDMDMDDHD...",
    "..DKDD.....MDDK............HHDDDDDHD....",
    "...KDDK...MDDKD............MHHKKKDD.....",
    "...MKDDDDDDDKD...............DDDDM......",
    ".....HHDDDDHD...........................",
    "......MKKKK.............................",
    "........................................",
  ],
  sprint_NE: [
    "............................................",
    "............................................",
    "............DHKKKK..........................",
    "...........DDMMjjjDD........................",
    "..........MMJJJJJjjjD.......................",
    "..........DJJJJjjjjjDM......................",
    "........MMDJJJjjjjjjjK......................",
    ".......MDDMJJJjjjjKKDHDDDDDM................",
    ".......DKDDDDDKjjjjDKDjjjMDMDM..............",
    "..........HMHHKKKKKDJJJJ..JJJjK.............",
    "..........HsMMSHHKJJJJJ..JJJJJJK............",
    "..........DSSMSHHjJJJJ..JJJJJJJJK...........",
    "..........DsSSsHDjDjJJ..JJJJJJJJjD..........",
    "..........DMSSsDJJJDjJ.JJJJJJjDDDK..........",
    "..........MDMSDMRJJDjJ.JJJjjKKKKKKM.........",
    "............MKDJWRjKjj.JJKKKHHHHHKD.........",
    "............MKDJJJKDKjJKKKHHHHHKHKD.........",
    "....DM...MHHKMsDjKM..DKKKDHHHHDKHKD.........",
    "...KDDKKKHMssSSsHM..MKKHHHHHHHKKKK..........",
    "...KDDHMSSSSSSsHM..DKKHHHHKKKKKKD...........",
    "...KKKMSSsMMMMHM..DKDKHHKKKKKKDKM...........",
    "...KDKDMDKDKDDDDDDKssDKKKKKKKKKD............",
    "...KMDHKMMMDJjMMjjKSSsHKKHMKDKD.............",
    "...DMDHKD.DMJDDDMDKSSSsKDjDDMK..............",
    "......HKKKKRDjMM..MDSSSHKKDMDD..............",
    "...MDKHDMDKRDKRMM..KMSSSHsKJjjDDDKKKKDM.....",
    "...DKDDHKKDJDKDRD..MHsSSMMKJMDKKHDDDDKKM....",
    "..DKDDH..DRjKDKDRDMRMHsSSKJDDMKDDDDDDDDKM...",
    ".MKDDD...DRDKDDKDJMMDKDMDKDKDjMKD...DDDDD...",
    ".DHDM...MMMDDDDKDDJMDHDKKHKKKKMMD.....MDKD..",
    ".DMK....DRDM..DDK.DRMKKKHHKKKHKRDM.....DDK..",
    ".DMK...DDMK...HDK.MDJDKHHKMKDDDjRKKM...DDDD.",
    ".DMK...DMDH...HDK..DKKKHKMKKKDRKjMDK...DDHK.",
    ".DDK...MKKM...DDK..DKDKKMKKKKKKKKJDHM..MDHK.",
    ".DDDD.........DDK..MKKKDKKKMMMMMJjKKM..DDHK.",
    "..KMD........MDKD...MDMDMDKKKKDDDKDM...KDHK.",
    "..DDDDM.....MDDKD....MDDDD.HDD...D.....DDKD.",
    "...KDDDM...DDDKD......MMM..KDDM..M....MDDK..",
    "....DHDDHDHDDHD............MKDD.......DDKD..",
    ".....DHDDDDKKD.............DKHDDD...MKDHD...",
    ".......DDDDM.................DHDDHDHDDKD....",
    "..............................DKKDDDKKD.....",
    "................................DDDDD.......",
    "............................................",
  ],
};

export const BIKE_PX = 0.49; // 1マスの実寸。人物(pixelPerson.jsx)と同じ値＝粒度が揃う

export function bikeLegend(color) {
  return {
    K: "#161616", D: "#3e3e3e", M: "#707070", R: "#a8a8a8", W: "#d8d8d8",
    J: color, j: shade(color, 0.68),
    S: "#f2c18e", s: "#cd9260", H: "#463223",
  };
}

// x,y: 接地点（車輪の下端中央）のワールド座標。color=チーム色（車体とジャージに使う）。
// posture: "normal" | "dancing" | "sprint"、dir: "SE" | "NE"
// flip: 画面左向きに進むとき true（activityFacesLeftの一般的な意味のまま）。
//
// 【注意】参考画像はSE/NEが独立した2枚の絵で、互いに鏡像の関係ではない。原本（矢印付きの
// 1枚目）を見るとSEは既定で左向き（矢印↙）、NEは既定で右向き（矢印↗）に描かれている。
// そのためNEはflip=trueのときだけ鏡像化すればよいが、SEは向きが逆なのでflip=falseの
// ときに鏡像化する必要がある（実機で「進行方向と鏡像の向きが逆」というユーザー指摘により
// 判明。SE/NEで反転条件を共通化していたのが原因だった）。
export function PixelBike({ x, y, color, posture = "normal", dir = "SE", flip }) {
  const frame = BIKE[`${posture}_${dir}`] || BIKE.normal_SE;
  const inner = pixelSprite(frame, bikeLegend(color), BIKE_PX,
    frame[0].length / 2, frame.length, "b", "#161616", false);
  const mirror = dir === "SE" ? !flip : !!flip;
  return (
    <g transform={`translate(${x.toFixed(1)},${y.toFixed(1)})`}>
      <ellipse cx="0" cy="0" rx="8.4" ry="2.2" fill="#000" opacity="0.22" />
      {mirror ? <g transform="scale(-1,1)">{inner}</g> : inner}
    </g>
  );
}
